### ISSUE TITLE
Issues with setup

### ISSUE THREAD

**Issue by zitterbewegung** [dmatrix/ray-core-tutorial#39]
These are your instructions:

python3 -m pip install -r requirements.txt
python3 -m ipykernel install p
git clone git@github.com:dmatrix/ray-core-tutorial.git
cd to <cloned_dir>

Should they be? 

git clone git@github.com:dmatrix/ray-core-tutorial.git
cd to <cloned_dir>
python3 -m pip install -r requirements.txt
python3 -m install ipykernel

**Comment by dmatrix** [comment]
@zitterbewegung I see your point, you need the requirements.txt before you can do the setup. good catch!

BTW there is typo `python3 -m ipykernel install p` should be `python3 -m ipykernel install`

**Comment by dmatrix** [comment]
fixed in PR #41
